services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - ./api.log:/app/api.log
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge